# Generated by Django 3.0.8 on 2020-08-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bangusu', '0002_auto_20200824_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
