# Generated by Django 3.0.8 on 2020-08-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bangusu', '0003_auto_20200824_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
