# Generated by Django 3.0.8 on 2020-09-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bangusu', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Предмет Заказа', 'verbose_name_plural': 'Предмет Заказа'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='stock',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
