# Generated by Django 3.0.8 on 2020-09-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bangusu', '0009_auto_20200901_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='stock',
            field=models.PositiveIntegerField(default='1'),
        ),
    ]
