# Generated by Django 3.0.8 on 2020-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bangusu', '0010_auto_20200902_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=56, max_length=2),
        ),
    ]
