# Generated by Django 3.0.8 on 2020-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bangusu', '0011_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='M', max_length=3),
        ),
    ]
